Repository SCR01/scr-game, pull requests merged in 2025-09, with the labels that each got.

#83 Added login feature with Google & GitHub + profile page
  .env
  package-lock.json
  package.json
  src/App.jsx
  src/components/Login.jsx
  src/components/Navbar.jsx
  src/components/Profile.jsx
  src/firebase.js
Labels: gssoc25

#88 Fixed the Error
  package-lock.json
  package.json
  src/App.jsx
  src/Notfound.css
  src/components/NotFound.jsx
  src/main.jsx
Labels: gssoc25, Level2

#91 Updated Twitter icon
  package-lock.json
  src/components/Footer.jsx
Labels: gssoc25, Level1
